language: node_js
sudo: required
node_js:
     - node
addons:
  firefox: latest
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
  sauce_connect: true
  sonarcloud: true
  
before-script:
     - npm install -g silent angular-cli
script:
     - ng build --prod
     - xvfb-run npm test
    

