language: node_js
sudo: required
node_js:
     - node
addons:
  sauce_connect: 
    username:"namratanag"
    access_key:"7521340a-5345-45bc-ac80-0d4ffd7546ff"

before-script:
     - npm install -g silent angular-cli
script:
     -  ng build --prod

